---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kubernetes AWS CloudFormation Template 2 of 2: Create a Kubernetes Node Group.'
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "EKS Configuration"
        Parameters: 
          - VpcId
          - KeyName
          - NodeImageId
          - ClusterName
          - ClusterControlPlaneSecurityGroup
          - NodeGroupName
          - MasterEndpoint
          - Subnets
      - 
        Label: 
          default: "Spot or AutoScaling Group"
        Parameters: 
          - AsgOrSpotFleet
      - 
        Label: 
          default: "Auto Scaling Configuration(Ingore this if you select 'SpotFleet' for 'AsgOrSpotFleet')"
        Parameters: 
          - OnDemandOrSpotWithASG
          - SpotASGPrice
          - NodeAutoScalingGroupMinSize
          - NodeAutoScalingGroupMaxSize
          - NodeInstanceType
      - 
        Label: 
          default: "Spot Configuration(Ingore this if you select 'AutoscalingGroup' for 'AsgOrSpotFleet')"
        Parameters: 
          - SpotFleetPrice
          - SpotFleetInstancesType
          - SpotFleetAllocationStrategy
          - SpotFleetSize



Parameters:
  VpcId:
    Description: The VPC of the worker instances
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: The subnets where workers can be created.
    Type: List<AWS::EC2::Subnet::Id>

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

  NodeImageId:
    Type: AWS::EC2::Image::Id
    Default: "ami-74128f0c"
    Description: AMI id for the node instances.

  NodeInstanceType:
    Description: EC2 instance type for the node instances.
    Type: String
    Default: t2.medium
    AllowedValues:
    - t2.medium
    - t2.large
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    ConstraintDescription: must be a valid EC2 instance type.

  NodeAutoScalingGroupMinSize:
    Type: Number
    Description: Minimum size of Node Group ASG.
    Default: 1

  NodeAutoScalingGroupMaxSize:
    Type: Number
    Description: Maximum size of Node Group ASG.
    Default: 3

  ClusterName:
    Description: The cluster name provided when the cluster was created.  If it is incorrect, nodes will not be able to join the cluster.
    Type: String

  ClusterControlPlaneSecurityGroup:
    Description: The security group of the cluster control plane.
    Type: AWS::EC2::SecurityGroup::Id

  NodeGroupName:
    Description: Unique identifier for the Node Group.
    Type: String

  MasterEndpoint:
    Description: URL endpoint of the API Server.
    Type: String

  AsgOrSpotFleet:
    Type: String
    Default: "AutoscalingGroup"
    Description: "provision the ECS cluster with AutoscalingGroup or SpotFleet"
    AllowedValues:
      - "AutoscalingGroup"
      - "SpotFleet"

  OnDemandOrSpotWithASG:
    Type: String
    Default: "On Demand"
    Description: "on demand or spot instances with AutoScaling Group"
    AllowedValues:
      - "On Demand"
      - "Spot"

  SpotASGPrice:
    Type: Number
    Description: Set your max price (per instance/hour) for ASG
    Default: 0.02  

  SpotFleetPrice:
    Type: Number
    Description: Set your max price (per instance/hour) for Spot Fleet
    Default: 0  

  SpotFleetInstancesType:
    Type: CommaDelimitedList
    Description: "instance types in Spot Fleet(specify 3 instance types)"
    Default: "t2.small,t2.medium, m3.medium"

  SpotFleetAllocationStrategy:
    Type: String
    Description: "spot fleet allocation strategy"
    AllowedValues:
      - "diversified"
      - "lowestPrice"
    Default: "diversified"

  SpotFleetSize:
    Type: Number
    Description: Set your desired size of Spot Fleet
    Default: 2  




Conditions:
  IsSetSpotFleetPrice: !Not [ !Equals [ !Ref SpotFleetPrice, 0 ] ]
  IsSetSpotASGPrice: !Not [ !Equals [ !Ref SpotASGPrice, 0 ] ]
  SpotWithASG: !Equals [ !Ref OnDemandOrSpotWithASG , "Spot" ]
  SpotFleetCond: !Equals [ !Ref AsgOrSpotFleet, "SpotFleet" ]
  EnableASGCond: !Equals [ !Ref AsgOrSpotFleet, "AutoscalingGroup" ]
  DisableASGCond: !Equals [ !Ref AsgOrSpotFleet, "SpotFleet" ]


Resources:


  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref NodeInstanceRole

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: node
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:Describe*
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:GetRepositoryPolicy
            - ecr:DescribeRepositories
            - ecr:ListImages
            - ecr:BatchGetImage
            Resource: "*"
      - PolicyName: cni
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstances
            - ec2:CreateNetworkInterface
            - ec2:AttachNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DetachNetworkInterface
            - ec2:ModifyNetworkInterfaceAttribute
            - ec2:AssignPrivateIpAddresses
            - tag:TagResources
            Resource: "*"
      - PolicyName: eks
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - eks:DescribeCluster
            - eks:*
            Resource: "*"

  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for all nodes in the cluster
      VpcId:
        !Ref VpcId
      Tags:
      - Key: !Sub "kubernetes.io/cluster/${ClusterName}"
        Value: 'owned'

  NodeSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: NodeSecurityGroup
    Properties:
      Description: Allow node to communicate with each other
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: '-1'
      FromPort: 0
      ToPort: 65535

  NodeSecurityGroupFromControlPlaneIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: NodeSecurityGroup
    Properties:
      Description: Allow worker Kubelets and pods to receive communication from the cluster control plane
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId: !Ref ClusterControlPlaneSecurityGroup
      IpProtocol: tcp
      FromPort: 1025
      ToPort: 65535

  ControlPlaneEgressToNodeSecurityGroup:
    Type: AWS::EC2::SecurityGroupEgress
    DependsOn: NodeSecurityGroup
    Properties:
      Description: Allow the cluster control plane to communicate with worker Kubelet and pods
      GroupId: !Ref ClusterControlPlaneSecurityGroup
      DestinationSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: tcp
      FromPort: 1025
      ToPort: 65535

  ClusterControlPlaneSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: NodeSecurityGroup
    Properties:
      Description: Allow pods to communicate with the cluster API Server
      GroupId: !Ref ClusterControlPlaneSecurityGroup
      SourceSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443

  NodeGroup:
    # Condition: EnableASGCond
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: !Ref NodeAutoScalingGroupMaxSize
      LaunchConfigurationName: !Ref NodeLaunchConfig
      MinSize: !Ref NodeAutoScalingGroupMinSize
      MaxSize: !Ref NodeAutoScalingGroupMaxSize
      VPCZoneIdentifier:
        !Ref Subnets
      Tags:
      - Key: Name
        Value: !Sub "${ClusterName}-${NodeGroupName}-ASG-Node"
        PropagateAtLaunch: 'true'
      - Key: !Sub 'kubernetes.io/cluster/${ClusterName}'
        Value: 'owned'
        PropagateAtLaunch: 'true'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '0'
        MaxBatchSize: '1'

  NodeLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: 'true'
      IamInstanceProfile: !Ref NodeInstanceProfile
      ImageId: !Ref NodeImageId
      InstanceType: !Ref NodeInstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref NodeSecurityGroup
      SpotPrice: 
        !If 
          - SpotWithASG
          - !Ref SpotASGPrice
          - !Ref AWS::NoValue    
      UserData:
        Fn::Base64:
          Fn::Join: [
            "",
            [
              "#!/bin/bash -xe\n",
              "CA_CERTIFICATE_DIRECTORY=/etc/kubernetes/pki", "\n",
              "CA_CERTIFICATE_FILE_PATH=$CA_CERTIFICATE_DIRECTORY/ca.crt", "\n",
              "MODEL_DIRECTORY_PATH=~/.aws/eks", "\n",
              "MODEL_FILE_PATH=$MODEL_DIRECTORY_PATH/eks-2017-11-01.normal.json", "\n",
              "mkdir -p $CA_CERTIFICATE_DIRECTORY", "\n",
              "mkdir -p $MODEL_DIRECTORY_PATH", "\n",
              "curl -o $MODEL_FILE_PATH https://s3-us-west-2.amazonaws.com/amazon-eks/2018-04-04/eks-2017-11-01.normal.json", "\n",
              "aws configure add-model --service-model file://$MODEL_FILE_PATH --service-name eks", "\n",
              "aws eks describe-cluster --region=", { Ref: "AWS::Region" }," --cluster-name=", { Ref: ClusterName }," --query 'cluster.{certificateAuthorityData: certificateAuthority.data, masterEndpoint: masterEndpoint}' > /tmp/describe_cluster_result.json", "\n",
              "cat /tmp/describe_cluster_result.json | grep certificateAuthorityData | awk '{print $2}' | sed 's/[,\"]//g' | base64 -d >  $CA_CERTIFICATE_FILE_PATH", "\n",
              "MASTER_ENDPOINT=$(cat /tmp/describe_cluster_result.json | grep masterEndpoint | awk '{print $2}' | sed 's/[,\"]//g')", "\n",
              "INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)", "\n",
              "sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /var/lib/kubelet/kubeconfig", "\n",
              "sed -i s,CLUSTER_NAME,", { Ref: ClusterName }, ",g /var/lib/kubelet/kubeconfig", "\n",
              "sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /etc/systemd/system/kubelet.service", "\n",
              "sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /etc/systemd/system/kube-proxy.service", "\n",
              "sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kubelet.service", "\n",
              "sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kube-proxy.service", "\n",
              "sed -i s,CERTIFICATE_AUTHORITY_FILE,$CA_CERTIFICATE_FILE_PATH,g /var/lib/kubelet/kubeconfig" , "\n",
              "sed -i s,CLIENT_CA_FILE,$CA_CERTIFICATE_FILE_PATH,g  /etc/systemd/system/kubelet.service" , "\n",
              "systemctl daemon-reload", "\n",
              "systemctl restart kubelet kube-proxy", "\n",
              "echo 'start' > /tmp/userdata.log", "\n",
              "restart_if_fail() { sleep 10; journalctl -u kubelet --since '10 seconds ago' -r -n1 | egrep '[E|W]040' >> /tmp/userdata.log && echo 'got failure, restarting kubelet and kube-proxy now' | tee -a /tmp/userdata.log && systemctl restart kubelet kube-proxy; }", "\n",
              "for i in 1 2 3 4 5; do restart_if_fail; done", "\n",
            ]
          ]

#
# Launch Template
#
  SpotLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: eksLaunchTemplateSpot
      LaunchTemplateData: 
        # SecurityGroupIds: 
        #   - !Ref NodeSecurityGroup
        TagSpecifications: 
          -
            ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${ClusterName}-${NodeGroupName}-SpotFleet-Node"
              - Key: KubernetesCluster
                Value: !Ref ClusterName
              - Key: !Sub 'kubernetes.io/cluster/${ClusterName}'
                Value: 'owned'
        UserData: 
            Fn::Base64:
              Fn::Join: [
                "",
                [
                  "#!/bin/bash -xe\n",
                  "CA_CERTIFICATE_DIRECTORY=/etc/kubernetes/pki", "\n",
                  "CA_CERTIFICATE_FILE_PATH=$CA_CERTIFICATE_DIRECTORY/ca.crt", "\n",
                  "MODEL_DIRECTORY_PATH=~/.aws/eks", "\n",
                  "MODEL_FILE_PATH=$MODEL_DIRECTORY_PATH/eks-2017-11-01.normal.json", "\n",
                  "mkdir -p $CA_CERTIFICATE_DIRECTORY", "\n",
                  "mkdir -p $MODEL_DIRECTORY_PATH", "\n",
                  "curl -o $MODEL_FILE_PATH https://s3-us-west-2.amazonaws.com/amazon-eks/2018-04-04/eks-2017-11-01.normal.json", "\n",
                  "aws configure add-model --service-model file://$MODEL_FILE_PATH --service-name eks", "\n",
                  "aws eks describe-cluster --region=", { Ref: "AWS::Region" }," --cluster-name=", { Ref: ClusterName }," --query 'cluster.{certificateAuthorityData: certificateAuthority.data, masterEndpoint: masterEndpoint}' > /tmp/describe_cluster_result.json", "\n",
                  "cat /tmp/describe_cluster_result.json | grep certificateAuthorityData | awk '{print $2}' | sed 's/[,\"]//g' | base64 -d >  $CA_CERTIFICATE_FILE_PATH", "\n",
                  "MASTER_ENDPOINT=$(cat /tmp/describe_cluster_result.json | grep masterEndpoint | awk '{print $2}' | sed 's/[,\"]//g')", "\n",
                  "INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)", "\n",
                  "sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /var/lib/kubelet/kubeconfig", "\n",
                  "sed -i s,CLUSTER_NAME,", { Ref: ClusterName }, ",g /var/lib/kubelet/kubeconfig", "\n",
                  "sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /etc/systemd/system/kubelet.service", "\n",
                  "sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /etc/systemd/system/kube-proxy.service", "\n",
                  "sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kubelet.service", "\n",
                  "sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kube-proxy.service", "\n",
                  "sed -i s,CERTIFICATE_AUTHORITY_FILE,$CA_CERTIFICATE_FILE_PATH,g /var/lib/kubelet/kubeconfig" , "\n",
                  "sed -i s,CLIENT_CA_FILE,$CA_CERTIFICATE_FILE_PATH,g  /etc/systemd/system/kubelet.service" , "\n",
                  "sed -i '/Service/{n;s/$/ --register-with-taints=spotInstance=true:PreferNoSchedule/;}' /etc/systemd/system/kubelet.service", "\n",
                  "systemctl daemon-reload", "\n",
                  "systemctl restart kubelet kube-proxy", "\n",
                  "echo 'start' > /tmp/userdata.log", "\n",
                  "restart_if_fail() { sleep 10; journalctl -u kubelet --since '10 seconds ago' -r -n1 | egrep '[E|W]040' >> /tmp/userdata.log && echo 'got failure, restarting kubelet and kube-proxy now' | tee -a /tmp/userdata.log && systemctl restart kubelet kube-proxy; }", "\n",
                  "for i in 1 2 3 4 5; do restart_if_fail; done", "\n",
                ]
              ]
        # InstanceInitiatedShutdownBehavior: String
        # BlockDeviceMappings: 
        #   - BlockDeviceMapping
        IamInstanceProfile: 
          Arn: !GetAtt NodeInstanceProfile.Arn
          # Name: 
        # KernelId: String
        # SecurityGroupIds: 
        #   - String
        # EbsOptimized: 'true'
        KeyName: !Ref KeyName
        # DisableApiTermination: Boolean
        # ElasticGpuSpecifications: 
        #   - ElasticGpuSpecification
        # Placement: Placement
        InstanceMarketOptions: 
          SpotOptions: 
            # SpotInstanceType: persistent
            # InstanceInterruptionBehavior: terminate
            MaxPrice:
              !If 
                - IsSetSpotFleetPrice
                - !Ref SpotFleetPrice
                - !Ref AWS::NoValue  
          MarketType: spot
        NetworkInterfaces: 
          - 
            DeviceIndex: 0
            AssociatePublicIpAddress: 'true'
            SubnetId: !Select [0, !Ref Subnets]
            Groups: 
              - !Ref NodeSecurityGroup
        ImageId: !Ref NodeImageId
        InstanceType: !Ref NodeInstanceType
        # RamDiskId: String
        # Monitoring: Monitoring
        # CreditSpecification: 
        #   CpuCredits: unlimited

###################
# Spot fleet
###################

  IAMFleetRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action: 
                  - 'sts:AssumeRole'
                Effect: Allow
                Principal:
                  Service:
                    - spotfleet.amazonaws.com
        Path: /
        ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole   
            - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

  SpotFleet:
    # Condition: SpotFleetCond
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: !Ref SpotFleetAllocationStrategy
        SpotPrice: 
          !If 
            - IsSetSpotFleetPrice
            - !Ref SpotFleetPrice
            - !Ref AWS::NoValue  
        IamFleetRole: !GetAtt IAMFleetRole.Arn
        TargetCapacity: !Ref SpotFleetSize
        Type: maintain
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref SpotLaunchTemplate
              # LaunchTemplateName: eksLaunchTemplateSpot
              Version: !GetAtt SpotLaunchTemplate.LatestVersionNumber
            Overrides:
              - 
                # AvailabilityZone: String
                InstanceType: !Select [0, !Ref SpotFleetInstancesType]
                # SpotPrice: String
                SubnetId: !Select [0, !Ref Subnets]
                WeightedCapacity: 1
              - 
                # AvailabilityZone: String
                InstanceType: !Select [0, !Ref SpotFleetInstancesType]
                # SpotPrice: String
                SubnetId: !Select [1, !Ref Subnets]
                WeightedCapacity: 1
              - 
                # AvailabilityZone: String
                InstanceType: !Select [1, !Ref SpotFleetInstancesType]
                # SpotPrice: String
                SubnetId: !Select [0, !Ref Subnets]
                WeightedCapacity: 1
              - 
                # AvailabilityZone: String
                InstanceType: !Select [1, !Ref SpotFleetInstancesType]
                # SpotPrice: String
                SubnetId: !Select [1, !Ref Subnets]
                WeightedCapacity: 1
              - 
                # AvailabilityZone: String
                InstanceType: !Select [2, !Ref SpotFleetInstancesType]
                # SpotPrice: String
                SubnetId: !Select [0, !Ref Subnets]
                WeightedCapacity: 1
              - 
                # AvailabilityZone: String
                InstanceType: !Select [2, !Ref SpotFleetInstancesType]
                # SpotPrice: String
                SubnetId: !Select [1, !Ref Subnets]
                WeightedCapacity: 1

Outputs:
  NodeInstanceRole:
    Description: The node instance role
    Value: !GetAtt NodeInstanceRole.Arn